services:

  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres123
        POSTGRES_DB: postgres
    ports:
        - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#    - 8080:8080
volumes:
  postgres_data:
